EventManagement_Project/Controllers/BookingEquipmentController.cs
using EventManagement_Project.Models;
using EventManagement_Project.Repository_Class;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Collections.Generic;

namespace EventManagement_Project.Controllers
{
    public class BookingEquipmentController : Controller
    {
        private readonly BookEqipmentRepos BookEqipmentRepos;
        public BookingEquipmentController(BookEqipmentRepos BookEqipmentRepos)
        {
            this.BookEqipmentRepos = BookEqipmentRepos;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Success()
        {
            return View();
        }
        public IActionResult EqipmentBook()
        {

            List<EquipmentModel> Equipments = BookEqipmentRepos.FeatchEquipments();
            TempData["Equipments"] = Equipments;
            string name = HttpContext.Session.GetString("Name");
            ViewData["Name"] = name;

            return View();
        }

        [HttpPost]
        public async Task<ActionResult> EqipmentBookings(string MODEL)
        {
            try
            {
                dynamic requestData = JsonConvert.DeserializeObject(MODEL);
                List<int> selectedEquipments = requestData.selectedEquipments.ToObject<List<int>>(); 
              
                var resultAdd = BookEqipmentRepos.BOOKEQIPMENT(selectedEquipments);

                if (resultAdd)
                {
                    return Json(new { IsSuccess = true, Message = "Data saved successfully" });
                }
                else
                {
                    return Json(new { IsSuccess = false, Message = "An Error Occurred" });
                }
            }
            catch (Exception)
            {
                return Json(new { IsSuccess = false, Message = "An unexpected error occurred" });
            }
        }

    }
}

EventManagement_Project/Views/BookingEquipment/EqipmentBook.cshtml
@model EventManagement_Project.Models.BookingEquipmentModel
@{
    string name = ViewData["Name"] as string;
}
<div class="container">
    <div class="row">
        <div class="col-md-6">
    <form method="post" enctype="multipart/form-data">
        <div class="col-xs-offset-0 col-xs-4">
            <div class="container-fluid service py-5">
                <div class="section-title  wow fadeInUp" data-wow-delay="0.2s">
                    <div class="sub-style">
                        <h4 class="sub-title px-3 mb-0">Booking Equipments</h4>
                    </div>
                </div>
            </div>
            <input asp-for="BookingEquipmentID" type="hidden" id="txtID" class="form-control" />

            <div class="form-group">
                <label>Equipments list</label>
                @if (TempData.ContainsKey("Equipments"))
                {
                    var EquipmentsList = TempData["Equipments"] as List<EquipmentModel>;
                    foreach (var Equipment in EquipmentsList)
                    {
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" name="selectedEquipments" id="equipment_@Equipment.EquipmentId" value="@Equipment.EquipmentId" data-img="@Equipment.EquipmentFilepath" onchange="changeImage(this)">
                                @Equipment.EquipmentName
                            </label>
                        </div>
                    }
                }
            </div>

            <br />
            <div class="form-group">
                <button type="button" onclick="Savedata()" class="btn btn-success">Book Equipment</button>
            </div>
        </div>

    </form>
</div>
        <div class="col-md-6">
            <div style="margin-top: 100px;">
                <img id="Image" src="" alt="Image" style="width:400px; height: 330px;">
            </div>
        </div>
    </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

<script src="~/js/EquipmentBooking.js"></script>

EventManagement_Project/Views/BookingEquipment/Success.cshtml
<h2>Booking Venu SuccessFully.......</h2>

<h1>Next Process Book Eqipment</h1>

<p>
    @Html.ActionLink("Click Here to Book Equipment", "EqipmentBook", "BookingEquipment")
</p>